### ISSUE TITLE
Nova página de texto simples

### ISSUE THREAD

**Issue by Yeie02** [Enois/timtec#101]
Precisamos de uma página de texto simples (como o Quem Somos) para colocar os nomes de todos que contribuíram via Catarse. Só será acessível via “quem somos”.

**Comment by brunosmartin** [comment]
Preciso do nome e conteúdo desta página.

**Comment by brunosmartin** [comment]
Énois vai fornecer o texto, com título, para inserir.
Vai ser um modal, como o "Conheça", dentro do menu quem somos no cabeçalho.
Definir nome q vai no menu quem somos.

**Comment by Yeie02** [comment]
Ei, Bruno, beleza?

A página vai chamar "Apoiadores" e o texto segue abaixo:


A Escola de Jornalismo é uma plataforma de cursos de comunicação, voltada
para o público jovem e gratuita, construída pela equipe da Énois |
Inteligência Jovem. Mas ela não é um trampo só nosso. Esta plataforma
contou com a contribuição de centenas de pessoas através do site de
financiamento coletivo Catarse.

A todos vocês, que acreditam no potencial transformador da educação e do
jornalismo, agradecemos e prometemos continuar esse trabalho com
compromisso e muita energia. Valeu!

Adriana Franco
Alanna Kern
Alexandre Seragini
Aline Cavalcante
Aline Kelly
Alvaro Almeida
Amanda Rahra
Ana Aranha
Ana Carolina Nunes
Ana Gouvea Bocchini
Ana Luísa D'Maschio
Ana Paula Berlinga
Anderson Costa
André Benevides
André Casanova
André Rodrigues
André Seiti
Andrea Lua
Andrea Resende
Barao Sarno
Bea Meira
Beatriz Bechelli
Beatriz Mendes
Beatriz Petrilli
Beatriz Torres
Ben Rhaiem Med
Bia
Bianca Weingrill
Bibiana Haygert
Brad Haynes
Bruna de Paula
Bruno Petri
Caio Tendolini
Camila Haddad
Camilla Salmazi
Cândido Azeredo
Carla Albertuni
Carla Bárbaro Venturelli
Carlota Mingolla
Carol Lara
Carolina
Carolina Aranha
Carolina de Queiroz Franco Oliveira
Carolina Ferrés
Carolina Motoki
Cecília Do Lago
Cedê Silva
Celsobessa
Cesar Sinicio Marques
Claudia Carmello
Claudia Pereira Weingrill
Cleber Arruda
Cynthia Rosenburg
Daniel Izzo
Daniela Bernardi
Daniela Monaco Raposo
Danielle Bidóia
David Leonardo
Diego Rabatone Oliveira
Dino Siwek
Duanne Ribeiro
Dudu Torres
Eduardo Nunomura
Emanuel Moura
Emmanuel Duarte
Erik Lopes
Fabiana Barbosa
Fabio Marabesi
Fatima Viscarra
Felipe Reis
Felipe Sad
Fernanda Barbosa
Fernando Pedron
Fernando Weingrill
Filipe Russo
Flávia Mantovani
Flavia Menani
Gabriel Mitani
Gabriela Cardoso Arthur
Gabriela Oliveira
Giba Canto
Giovana Sanchez
Gisela Blanco
Gladys Mariotto
Gui Neves
Guilherme Turri
Guilherme Yazaki
Gustavo De Boni
Gut Simon
Harrison Kobalski
hTrevisani
Igor Paulin da Silva
Isys Remião
Jaana Pinheiro
jadete calisto da silva
Jessica Leão
João Fellet
Joao Markun
Jose Carlos N Medeiros
Juliana Borges
Juliana De Faria Kenski
Juliana Mota Giopato
karina Prestes Pereira da Silva
Katia Assad
Katiane Romero
Larissa Ribeiro
Larissa Soriano
Laura Mantovanini Guedes
Laura Nascimento
Laura Sobenes
Leo Yu
Leonardo Sakamoto
Lilian Calmon
Lilian Starobinas
Lindolfo Reinert
Lisa Gunn
Lívia Laranjeira Souza
Luana Palmares
Lucas Albin
Lucas de Castro
Luciana Bobadilha
Luciana D Anunciação
Luis Fernando Guggenberger
Luiz Santelli
Maíla
Maíra Termero
Maíra Terra
Maís Moreno
Maitê Hotoshi
Marcela Amorozo Francisco
Marcela Diorio
Marcella Chartier
Marcelo Falciano
Márcio André de Melo Gomes
Marcos Salles
Maria Clara Matos
Maria De Fatima Gallinari
Maria Paola de Salvo
Mariana Tiso
Mariana Vitule
Marília Bueno
Marília Filgueiras
Mayra Rosa
Murilo Casagrande Modolo
Natacha
Natalia Barbosa
Natalie Reinoso
Nathalie Nahas
Nayara Ruiz
Paola Jacomel Laidane
Paula Desgualdo
Paula Feck
Paula Resende
Pedro Belo
Pedro Markun
Pollyanna Alves
Priscila Gonsales
Quequeré Jogos
Rafael
Rafael Tosta
Raphael Bottino
Raquel Pereira Clare
Regina Borba
Renato De Paiva Guimaraes
Renato Garcia
ricardobferraz
Richard Romancini
Rodrigo Alvarez
Rodrigo Ormezzano Neto
Rodrigo V Cunha
Sato DoBrasil
Sérgio Spagnuolo
Simone Cunha
Suelyen jou laureano
suraia calixto
Suzel Figueiredo
Taissa Castro
Talita Nozomi Kusunoki
Talitha Brinati Dornelas
Tatiana Bittencourt Moraes
Tatiana Cobbett
Teresa Nunes
Thiago Rosenberg
Thiago Teixeira
Tomás de Lara
Ton Messa
Vanessa Ribeiro
Vanessa Scheffer
Vera Lucia Ladeira Colonelli
Veri Soares
vimenegolo
Vinicius Leandro Gonçalves
Viviane Beatriz Costa
Wagner Cafagni Borja
Wania Spada Granja
Willians Romano
Ximena Leiva
Yan Boechat


Em 13 de abril de 2015 17:17, Bruno Martin <notifications@github.com>
escreveu:

> Énois vai fornecer o texto, com título, para inserir.
> Vai ser um modal, como o "Conheça", dentro do menu quem somos no cabeçalho.
> Definir nome q vai no menu quem somos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Enois/timtec/issues/101#issuecomment-92485771>.
>



-- 
*Érica Teruel *- Editora
Énois Conteúdo <http://enoisconteudo.com.br/>
11 2506 9601
11 9 6295 1761
