### ISSUE TITLE
Visualização dos professores na home 

### ISSUE THREAD

**Issue by Yeie02** [Enois/timtec#123]
Tá dando um bug na visualização dos professores, quando o varalzinho roda, eles estão se sobrepondo.  

![image](https://cloud.githubusercontent.com/assets/8915634/6006678/68e1a178-aafb-11e4-9116-c9aedb961c79.png)

**Comment by brunosmartin** [comment]
Funcionou na última versão do Firefox e chrome, no linux, testado 06/04
