### ISSUE TITLE
E-mail dos mentores

### ISSUE THREAD

**Issue by Yeie02** [Enois/timtec#40]
Capi, precisamos ter uma opção de mostrar ou não o e-mail do professor.

**Comment by brunosmartin** [comment]
Esconder o email, mostrar quando o usuário clica.

**Comment by brunosmartin** [comment]
O email agora é totalmetne oculto dos usuário anônimos (que não fizeram login) e os usuário atutenticados precisa clicar em um botão para ver o email.

**Comment by Yeie02** [comment]
Perfeito!

Em 11 de abril de 2015 21:32, Bruno Martin <notifications@github.com>
escreveu:

> O email agora é totalmetne oculto dos usuário anônimos (que não fizeram
> login) e os usuário atutenticados precisa clicar em um botão para ver o
> email.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Enois/timtec/issues/40#issuecomment-91954184>.
>



-- 
*Érica Teruel *- Editora
Énois Conteúdo <http://enoisconteudo.com.br/>
11 2506 9601
11 9 6295 1761
