### ISSUE TITLE
Cadastro não está funcionando 

### ISSUE THREAD

**Issue by Yeie02** [Enois/timtec#86]
Tento fazer o cadastro, ele pensa, pensa e aparece o bom e velho 404: 

![image](https://cloud.githubusercontent.com/assets/8915634/5902019/16a04b50-a55e-11e4-9831-0cda934a0c68.png)

**Comment by brunosmartin** [comment]
Preciso de acesso ao servidor de DNS.

**Comment by Yeie02** [comment]
Bruno, beleza?

Não tenho certeza se é isso... Capi disse que é pelo marcaria.com. O usuário
é nweingrill@gmail.com e a senha é josesn20

me diz se deu certo?

brigadão

2015-03-22 12:57 GMT-03:00 Bruno Martin <notifications@github.com>:

> Preciso de acesso ao servidor de DNS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Enois/timtec/issues/86#issuecomment-84641303>.
>



-- 
*Érica Teruel *- Editora
Énois Conteúdo <http://enoisconteudo.com.br/>
11 2506 9601
11 9 6295 1761
