### ISSUE TITLE
Falta espaçamento em biografia 

### ISSUE THREAD

**Issue by Yeie02** [Enois/timtec#88]
Quando um usuário (tanto "aluno" como mentor) cadastra uma bio, na visualização ela aparece sem os espaçamentos entre parágrafos. 

![image](https://cloud.githubusercontent.com/assets/8915634/5904219/2125bf14-a56e-11e4-99de-4d782cc4fe04.png)

**Comment by Yeie02** [comment]
Oi, Bruno! Então, essa parece não ter sido resolvida.

**Comment by brunosmartin** [comment]
O texto da biografia não está formatadado.

**Comment by Yeie02** [comment]
Oi, Bruno, beleza?

Então, editei algumas pra ver se aparecia o espaçamento, mas continua sem.
No entanto, misteriosamente, a do Raphael Erichsen aparece. Tenho que
editar no django, né?

brigada
abs

2015-04-15 19:56 GMT-03:00 Bruno Martin notifications@github.com:

> Closed #88 https://github.com/Enois/timtec/issues/88 via 73b7d6a
> https://github.com/Enois/timtec/commit/73b7d6a558a60c388e42157e73a1c132d5f4bcf5
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Enois/timtec/issues/88#event-282601852.

## 

*Érica Teruel *- Editora
Énois Conteúdo http://enoisconteudo.com.br/
11 2506 9601
11 9 6295 1761

**Comment by brunosmartin** [comment]
Vc tem q deixar uma linha em branco entre os parágrafos (dar doía enters).
Em 16/04/2015 12:07, "Yeie02" notifications@github.com escreveu:
