### ISSUE TITLE
Tags não estão aparecendo

### ISSUE THREAD

**Issue by Yeie02** [Enois/timtec#89]
Em trampos, coloquei tags, mas elas não estão aparecendo

![image](https://cloud.githubusercontent.com/assets/8915634/5904450/9ee0c010-a56f-11e4-86d0-63bd762595ba.png)

**Comment by Yeie02** [comment]
Oi, Bruno! Tá aparecendo, mas não como no layout. 

Como isso demoraria mais pra mudar, rola apenas escrever "tags" antes? E separar entre vírgulas?

**Comment by brunosmartin** [comment]
Colocar palavra "Tags:" na frente das tags e separa por vírgulas.

Colocar na mesma cor do título do trampo (opcional)
